import mongoose from 'mongoose';
import crypto from 'crypto';
import connectToDatabase from './db';

const getSessionModel = async () => {
  await connectToDatabase();
  const SessionSchema = new mongoose.Schema({
    key: {
      type: String,
      default: () => crypto.randomUUID().slice(-12),
      unique: true,
    },
    name: { type: String, required: true },
    host: [String],
    registrationNumber: String,
    description: { type: String },
    bracketLink: { type: String },
    serverInviteLink: { type: String },
    isPrivate: { type: Boolean },
    maxTeams: { type: Number },
    maxTeamSize: { type: Number },
    matchTeamSize: { type: Number },
    metas: [String],
    state: { type: String },
    currentRoundNumber: { type: Number },
    totalRounds: { type: Number },
    factions: [String],
    movesetsRequired: { type: Boolean },
    movesetsVisible: { type: Boolean },
    purifiedRequired: { type: Boolean },
    purifiedVisible: { type: Boolean },
    bestBuddyRequired: { type: Boolean },
    bestBuddyVisible: { type: Boolean },
    nicknameRequired: { type: Boolean },
    cpRequired: { type: Boolean },
    cpVisible: { type: Boolean },
    hpRequired: { type: Boolean },
    hpVisible: { type: Boolean },
    isTeamDraft: { type: Boolean },
    isGlobalDraft: { type: Boolean },
    registrationClosed: { type: Boolean },
    concluded: { type: Boolean },
    hideTeamsFromHost: { type: Boolean, default: false },
    hideFromGuests: { type: Boolean, default: false },
    roundStartTime: { type: Date },
    timeControl: { type: Number, default: 0 },
    players: [{
      playerId: String,
      factionId: String,
      tournamentPosition: Number,
      opponents: [String],
      receivedBye: { type: Boolean, default: false },
      pairedUpDown: { type: Boolean, default: false },
      removed: { type: Boolean, default: false },
      rating: { type: Number },
      metaClass: { type: String },
      pokemon: [{
        sid: { type: Number },
        speciesName: { type: String },
        cp: { type: Number },
        hp: { type: Number },
        chargedMoves: [String],
        fastMove: { type: String },
        best_buddy: { type: Boolean, default: false },
        shadow: { type: Boolean, default: false },
        purified: { type: Boolean, default: false },
        nickname: { type: String },
      }],
      wins: { type: Number },
      losses: { type: Number },
      gameWins: { type: Number },
      gameLosses: { type: Number },
      teamsByRound: [{
        round: { type: Number },
        pokemon: [
          {
            sid: { type: Number },
            speciesName: { type: String },
            cp: { type: Number },
            hp: { type: Number },
            chargedMoves: [String],
            fastMove: { type: String },
            best_buddy: { type: Boolean, default: false },
            shadow: { type: Boolean, default: false },
            purified: { type: Boolean, default: false },
            nickname: { type: String },
          },
        ],
      }],
    }],
    bracketType: { type: String },
    gameAmount: { type: Number },
    byeAward: { type: Number, default: 1 },
    playAllMatches: { type: Boolean, default: false },
    requireBothPlayersToReport: { type: Boolean, default: false },
    bracket: [{
      round: { type: Number },
      matches: [
        {
          seed: { type: Number },
          score: [[Number]],
          disputed: [{ type: Boolean, default: false }],
          touched: [{ type: Boolean, default: false }],
          factions: [{
            factionId: { type: String },
            score: [Number],
            removed: { type: Boolean, default: false },
          }],
          participants: [[{
            playerId: { type: String },
            score: [Number],
            touched: { type: Boolean, default: false },
            removed: { type: Boolean, default: false },
          }]],
          win: {
            round: Number,
            match: Number,
          },
          loss: {
            round: Number,
            match: Number,
          },
        },
      ],
    }],
  });
  return mongoose.models.session || mongoose.model('session', SessionSchema);
};

export default getSessionModel;
